name: job-finder
services:

  database:
    image: postgres:16
    container_name: postgres_job_finder
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  be-job-finder:
    container_name: be-job-finder
    build:
      context: ./../
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: "java.app.{{.Name}}"
        labels: "env,service,component,version"
        fluentd-async: 'true'
    volumes:
      - type: bind
        source: ./app/application.properties
        target: /app/application.properties
        read_only: true
      - type: bind
        source: ./app/logback.xml
        target: /app/logback.xml
        read_only: true
      - app_logs:/app/logs
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/be-jobfinder/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  app_logs:
