spring.application.name=jobfinder
spring.profiles.active=PROD

# questo é indicato nei controller perché altrimenti obbligava a legare '/api/v1' anche all' actuator
#spring.mvc.servlet.path=/be-jobfinder/api/v1
apiPath=/api/v1
server.port=8080

# healthcheck
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
management.endpoint.prometheus.enabled=true
# Definire un base path separato per gli endpoint actuator. Questo serve per omettere /api/v1 da questi endpoint
management.endpoints.web.base-path=/be-jobfinder/actuator

# logging
logging.config=${user.dir}/logback.xml

# H2
spring.datasource.url=jdbc:h2:file:${user.dir}/database/jobfinder_prod
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# abilita la console web
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# strategia di inizializzazione del database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# config
job.posting.max.candidates=${JOB_POSTING_MAX_CANDIDATES}
job.posting.language.handling=${JOB_POSTING_LANGUAGE_HANDLING}
job.posting.language.preferred=${JOB_POSTING_LANGUAGE_PREFERRED}
job.posting.keywords.positive=${JOB_POSTING_KEYWORDS_POSITIVE}
job.posting.keywords.negative=${JOB_POSTING_KEYWORDS_NEGATIVE}
config.selector.company=${CONFIG_SELECTOR_COMPANY}
config.selector.title=${CONFIG_SELECTOR_TITLE}
config.selector.location=${CONFIG_SELECTOR_LOCATION}
config.selector.postedDate=${CONFIG_SELECTOR_POSTEDDATE}
config.selector.candidates=${CONFIG_SELECTOR_CANDIDATES}
config.selector.body=${CONFIG_SELECTOR_BODY}
config.selector.containerCard=${CONFIG_SELECTOR_CONTAINERCARD}
config.selector.infoJob1=${CONFIG_SELECTOR_INFOJOB1}
config.selector.infoJob2=${CONFIG_SELECTOR_INFOJOB2}
